### ISSUE TITLE
Atom vs VSCode 

### ISSUE THREAD

**Issue by sirgalleto** [rebornix/vscode-nova#1]
I was using Nova for a long time, but in my recent change to VSCode, I feel something different. Are you using other specification for the theme? I mean, the VSCode theme is really different than the Atom theme. 

# Atom

![image](https://user-images.githubusercontent.com/5873627/30527573-17ee7bb8-9bf0-11e7-9d0d-df099aeb0a13.png)

# VSCode 

![image](https://user-images.githubusercontent.com/5873627/30527594-2fed5478-9bf0-11e7-9ee5-89edec824005.png)

Are you planning to merge the styles or something like that? I may help to create a PR.

**Comment by trevordmiller** [comment]
Yeah, @rebornix is working on updating the VSCode theme (which was never finished or officially recommended by Nova); once it uses the `nova-colors` package fully (only using the defined colors, for the correct mappings), I'll add it to [the website](https://trevordmiller.com/projects/nova) and share it as an official plugin :) @rebornix, let me know when you are ready for me to do this. Thank you!

Related issue: https://github.com/trevordmiller/nova-colors/issues/18

**Comment by trevordmiller** [comment]
Also, the Atom theme is also a bit out of date, the tabs need to be updated to match the Vim theme like this:

![image](https://user-images.githubusercontent.com/5497885/30561301-cac09a14-9c77-11e7-8d58-ea381839d4cc.png)

![image](https://user-images.githubusercontent.com/5497885/30561307-cf6225e2-9c77-11e7-89b3-a1c5f49218c8.png)

**Comment by sirgalleto** [comment]
I'd like to take some action items to make the necessary changes in an agile way. 

1. @trevordmiller Could you give us a kind off expect document of how Nova-vim looks like and how the theme should look like? 
2. @rebornix Could you create a way to track the to-do tasks? Maybe using issues or a Github project. 

Then I can help you with some PRs. 

Thanks!

**Comment by rebornix** [comment]
@sirgalleto I just released a new version of workbench theming and deprecated the old tmtheme file. At this particular moment, https://github.com/rebornix/vscode-nova/blob/master/themes/nova.json is the single source of truth. I didn't make updates to build scripts as I'd like to make this file mature and then replace all the hard code color hex value to predefined variable names.

In overall, there are two major things to do:

* TM Theme. Atom Nova overrides Atom's CSS rules instead of creating TM Theme. It's kind of hard to map Atom rules to TM tokens. What I do right now is
  * Open the same project in both VSCode and Atom
  * Inspect TM Tokens in VSCode, Open Developer Tools in Atom, compare between them if the color of a varaible/property/function is not correct. Add the new color rule to https://github.com/rebornix/vscode-nova/blob/master/themes/nova.json
* Workbench Theme
  * VSCode has a good documentation about which part can be customized, which can not be https://code.visualstudio.com/docs/getstarted/theme-color-reference . I tried to align it with Vim or Atom, however there are quite a few concepts or UI elements that Atom/Vim don't have, I pick a color that makes sense to me.

@sirgalleto feel free to play with the latest theme and if you see any color that doesn't seem right, you can tweak the json file directly. I would try to see what's missing there and log them in this repo. Thank you for helping out ;)

**Comment by trevordmiller** [comment]
@sirgalleto @rebornix The `nova-colors` package source itself defines variables for how each color should be used depending on the context:
https://github.com/trevordmiller/nova-colors/blob/master/src/index.js#L25-L73

The nova-vim theme is the best example of a Nova implementation. Please use it as your example instead of Atom:
https://github.com/trevordmiller/nova-vim/blob/master/src/index.js#L21-L272

Thank you!

**Comment by trevordmiller** [comment]
I'm posting some specific items of feedback as repo issues: https://github.com/rebornix/vscode-nova/issues

**Comment by rebornix** [comment]
@sirgalleto I went through issues created by Trevor, some of them are fixed, some of them are upstream issue/fr, but there are still three tasks can be done https://github.com/rebornix/vscode-nova/issues/9 , https://github.com/rebornix/vscode-nova/issues/7 , https://github.com/rebornix/vscode-nova/issues/5 .

**Comment by sirgalleto** [comment]
Thanks!

**Comment by xavadu** [comment]
any update on this? :)

**Comment by trevordmiller** [comment]
As shown on [the Nova website](https://trevordmiller.com/projects/nova),
![image](https://user-images.githubusercontent.com/5497885/32288581-fa7138dc-bef9-11e7-8b00-3adbc60abc86.png)

VSCode has been updated to implement Nova as much as it is able. There are still some areas where VSCode is not as flexible as Vim/Atom etc. as mentioned in this repo's issues but I would say this issue can be closed @rebornix :)

**Comment by xavadu** [comment]
Hi @trevordmiller not really, 
Check it:

[Reference](https://trevordmiller.com/projects/nova) 
![image](https://user-images.githubusercontent.com/1382820/32324715-98168588-bfcc-11e7-8435-023408efbd84.png)

The theme out of the box with the latest VSCode (1.17.2)
![image](https://user-images.githubusercontent.com/1382820/32324740-acf60e1a-bfcc-11e7-8f8f-93e5a616d6bc.png)

Theme with the manual changes that I did in the VSCode settings https://github.com/rebornix/vscode-nova/issues/12
![image](https://user-images.githubusercontent.com/1382820/32324791-d8bf5f4c-bfcc-11e7-831a-57163da6a464.png)

Still not perfect, but a bit better.. 

All the screenshot are just taken with the latest version of VSCode and VSCode-nova
The theme is wonderful, it would be a pity to have it sketchy for VSCode

Thanks!

**Comment by trevordmiller** [comment]
@xavadu "There are still some areas where VSCode is not as flexible as Vim/Atom etc. as mentioned in this repo's issues". See the specific open issues: https://github.com/rebornix/vscode-nova/issues. But this is up to @xavadu as I don't use or work on the VSCode theme :) I'd love to see it more fully support Nova as other plugins do but I know @rebornix has said that VSCode is limited.

**Comment by trevordmiller** [comment]
I'd suggest this issue be closed in favor of the more specific open issues iin https://github.com/rebornix/vscode-nova/issues.

**Comment by xavadu** [comment]
yes, I agree to close this one and keep the specific ones open.

But as I demonstrate you with the screenshots, there are a lot of thing supported by VSCode and not implemented actually by Nova.

**Comment by trevordmiller** [comment]
@xavadu Sounds good. Open up specific issues for @rebornix when he has time :)

**Comment by rebornix** [comment]
Let's focus on specific/workable issues, thanks everyone for your help on this.
